create table if not exists public.users (
  id text primary key,
  email text not null,
  name text,
  provider text not null default 'google',
  last_login timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.machines (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  position_x double precision not null default 0,
  position_y double precision not null default 0,
  position_z double precision not null default 0,
  sensors jsonb not null default '[]'::jsonb,
  images jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  object_id text,
  is_real_data boolean not null default false,
  severity text not null default 'INFO',
  timestamp timestamptz not null default now(),
  user_email text
);

create table if not exists public.chat_logs (
  id bigint generated by default as identity primary key,
  prompt text not null,
  response text not null default '',
  user_email text,
  timestamp timestamptz not null default now()
);

create table if not exists public.fallback_logs (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  success boolean not null,
  reason text not null,
  details jsonb not null default '{}'::jsonb,
  timestamp timestamptz not null default now()
);

alter table public.machines enable row level security;
create policy "Users manage their own machines" on public.machines
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

alter table public.users enable row level security;
create policy "Users read their own profile" on public.users
  for select using (id = auth.jwt() ->> 'email');
